[dependency-groups]
dev = []

[tool.pyright]
venv = ".venv"
venvPath = "."
typeCheckingMode = "standard"

[tool.uv]
managed = true
package = false

[tool.uv.workspace]
members = ["src/*"]

[tool.ruff]
indent-width = 4
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
