[project]
name = "fastapi-mcp-server"
readme = "README.md"
version = "0.0.1"

requires-python = ">=3.13"
dependencies = ["fastapi-mcp>=0.3.3", "mcp==1.7.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
